apiVersion: v1
kind: PersistentVolume
metadata:
  name: openg2perpsql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openg2perpsql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: openg2p-erp
  name: openg2perpsql
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: openg2p-erp
    tier: openg2perpsql
  clusterIP: None

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openg2p-erp
  name: openg2perpsql
spec:
  selector:
    matchLabels:
      app: openg2p-erp
      tier: openg2perpsql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: openg2p-erp
        tier: openg2perpsql
    spec:
      containers:
        - image: us.icr.io/phee-ns/postgres-odoo:latest
          name: postgresql
          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
          env:
            - name: POSTGRES_DB
              value: openg2p
            - name: POSTGRES_USER
              value: openg2p
              
          ports:
            - containerPort: 5432
              name: openg2perpsql
          volumeMounts:
            - name: openg2perpsql-initdb
              mountPath: /docker-entrypoint-initdb.d/
            - name: openg2perpsql-persistent-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: openg2perpsql-initdb
          configMap:
            name: openg2perpsql-initdb
        - name: openg2perpsql-persistent-storage
          persistentVolumeClaim:
            claimName: openg2perpsql-pv-claim